### ISSUE TITLE
Leo

### ISSUE THREAD

**Issue by Amymcdougall** [lockedata/locketweet#13]
Blogs with leo onndont work as he doesn't have a chibi to call

**Comment by maelle** [comment]
Will he ever get one? If he doesn't, maybe the function should

* use Steph's chibi

* and the text will be _this_ blog post instead of _my_ blog post?

What do you think?

**Comment by Amymcdougall** [comment]
Leo has left us now so he won't get one. Yes use Steph's chibi instead with 'this' blog post 🙂🙂
