### ISSUE TITLE
Weird title punctuation 

### ISSUE THREAD

**Issue by Amymcdougall** [lockedata/locketweet#14]
Https://itsalocke.com/blog/why-data-people-dont-do-devops/

**Comment by Amymcdougall** [comment]
https://itsalocke.com/blog/using-purrr-with-apis--revamping-my-code/

**Comment by maelle** [comment]
![image](https://user-images.githubusercontent.com/8360597/41215665-b9f3ae14-6d51-11e8-94bf-61857c7f50fd.png)

**Comment by maelle** [comment]
![image](https://user-images.githubusercontent.com/8360597/41215691-d48ef558-6d51-11e8-8c53-ac84cd2ca682.png)
