### ISSUE TITLE
Blogs with long titles are getting cut short

### ISSUE THREAD

**Issue by Amymcdougall** [lockedata/locketweet#16]
![screen shot 2018-06-04 at 13 43 08](https://user-images.githubusercontent.com/33873874/40918106-3e3bc206-67fd-11e8-8f9c-0a76265fb9bd.png)

https://itsalocke.com/blog/r-quick-tip-parameter-re-use-within-rmarkdown-yaml/

**Comment by maelle** [comment]
For the record, I'll make the title shorter when it has more than 70 characters.

I used 

```r
df =locketweet::lockedata_blog
df$title_lengths <- purrr::map_dbl(df$title, 
                                   stringi::stri_length)
df <- dplyr::arrange(df, -title_lengths)
locketweet::webshot_prettyplease(df$url[1])
```

to "debug".
